import type { CSSProperties } from 'react';

export default function CtaSection() {
  return (
    <div
      data-framer-name={"CTA"}
      className={"framer-4mzpau"}
      dangerouslySetInnerHTML={{ __html: "<div class=\"framer-zs6xvv\" data-framer-name=\"BKG\"><div class=\"framer-1g4p1zw-container\"><!--$--><video src=\"https://framerusercontent.com/assets/JYiGsWnrrEcKXGrpJouP1eGE8A.webm\" loop preload=\"none\" muted playsinline style=\"cursor:auto;width:100%;height:100%;border-radius:0px;display:block;object-fit:cover;background-color:rgba(0, 0, 0, 0);object-position:50% 50%\"></video><!--/$--></div></div><div class=\"framer-rgvy5d\" data-framer-name=\"Content\"><div class=\"framer-1dl4koe\" data-framer-name=\"Header\" data-framer-component-type=\"RichTextContainer\" style=\"transform:none\"><h6 class=\"framer-text framer-styles-preset-rznr2h\" data-styles-preset=\"GGOfIZbG_\" dir=\"auto\">The creative class sets the standard.</h6></div><div class=\"ssr-variant\"><div class=\"framer-1m0uuuq-container\"><!--$--><a class=\"framer-wElTP framer-TMtW3 framer-ya3xl7 framer-v-wdat6w framer-zre1el\" data-framer-name=\"Light->Brand\" data-border=\"true\" href=\"https://calendly.com/partnerships-contra/contra-labs-partnership-request\" target=\"_blank\" style=\"--border-bottom-width:1px;--border-color:rgba(145, 137, 137, 0.4);--border-left-width:1px;--border-right-width:1px;--border-style:solid;--border-top-width:1px;backdrop-filter:none;background-color:var(--token-bc95b61a-a7e2-421b-af5d-ae02de34d353, rgb(251, 250, 246));-webkit-backdrop-filter:none;height:100%;border-bottom-left-radius:24px;border-bottom-right-radius:24px;border-top-left-radius:24px;border-top-right-radius:24px\"><div class=\"framer-2jo82p\" data-framer-name=\"Hover Fill\" style=\"background-color:var(--token-97a39cd4-7a89-477d-8e83-6eb15404c07f, rgb(165, 190, 186));border-bottom-left-radius:10000px;border-bottom-right-radius:10000px;border-top-left-radius:10000px;border-top-right-radius:10000px;opacity:0\"></div><div class=\"framer-1y6rc17\" data-framer-name=\"Label\"><div class=\"framer-1s707a6\" data-framer-name=\"Start\" data-framer-component-type=\"RichTextContainer\" style=\"--framer-paragraph-spacing:0px;--extracted-r6o4lv:var(--token-41862f85-d984-4269-90b9-0c207a5502ff, rgb(43, 43, 41));transform:none\"><p class=\"framer-text framer-styles-preset-13z784r\" data-styles-preset=\"UHRxdad4O\" dir=\"auto\" style=\"--framer-text-color:var(--extracted-r6o4lv, var(--token-41862f85-d984-4269-90b9-0c207a5502ff, rgb(43, 43, 41)))\">Request partnership</p></div><div class=\"framer-1v90oc1\" data-framer-name=\"End\" data-framer-component-type=\"RichTextContainer\" style=\"--extracted-r6o4lv:var(--token-41862f85-d984-4269-90b9-0c207a5502ff, rgb(43, 43, 41));--framer-paragraph-spacing:0px;transform:none\"><p class=\"framer-text framer-styles-preset-13z784r\" data-styles-preset=\"UHRxdad4O\" dir=\"auto\" style=\"--framer-text-color:var(--extracted-r6o4lv, var(--token-41862f85-d984-4269-90b9-0c207a5502ff, rgb(43, 43, 41)))\">Request partnership</p></div></div></a><!--/$--></div></div></div>" }}
    />
  );
}
